filters:

  - filter_type: file
    source_language: en
    source_file: firefox-ios/Ecosia/L10N/en.lproj/Ecosia.strings
    file_format: STRINGS
    translation_files_expression: 'firefox-ios/Ecosia/L10N/<lang>.lproj/Ecosia.strings'

  - filter_type: file
    source_language: en
    source_file: firefox-ios/Ecosia/L10N/en.lproj/Plurals.stringsdict
    file_format: STRINGSDICT
    translation_files_expression: 'firefox-ios/Ecosia/L10N/<lang>.lproj/Plurals.stringsdict'
