version: 2.1

parameters:
  deploy-release:
    type: boolean
    default: false

orbs:
  macos: circleci/macos@2

jobs:
  build-testflight-deploy:
    environment:
      CI: true
    macos:
      xcode: "16.2"
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: Check for MARKETING_VERSION change
          command: sh ./check_marketing_version.sh
      - macos/switch-ruby:
          version: "3.2"
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: verify github
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: extract Production XCConfig
          command: echo "$PRODUCTION_XCCONFIG" | base64 --decode > firefox-ios/Client/Configuration/Production.xcconfig
      - run:
          name: Execute bootstrap
          command: ./bootstrap.sh
      - run:
          name: Build and deploy to Testflight
          no_output_timeout: 35m
          command: bundle exec fastlane testflight_live
              
workflows:
  deploy-release:
    when: << pipeline.parameters.deploy-release >>
    jobs:
      - build-testflight-deploy