# Uncomment the lines below you want to change by removing the # in the beginning

# ios_version("17.5")

# A list of devices you want to take the screenshots from
devices([
  "iPhone 15",
#   "Apple TV 1080p",
#   "Apple Watch Series 6 - 44mm"
])

languages([
  "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

scheme("Ecosia")
configuration("Debug")
app_identifier("com.ecosia.ecosiaapp")
test_target_name("EcosiaSnapshotTests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
reinstall_app(true)
number_of_retries(2)
disable_package_automatic_updates(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
