#!/usr/bin/env node
// Reads 01.color-primitive.tokens.json from firefox-ios/design-tokens/
// and writes firefox-ios/Ecosia/UI/DesignSystem/EcosiaColor.swift.
// Triggered by .github/workflows/sync-design-tokens.yml on every Figma push.

'use strict';

const fs   = require('fs');
const path = require('path');

const TOKENS_DIR  = path.join(__dirname, '..', 'firefox-ios', 'design-tokens');
const OUTPUT_PATH = path.join(__dirname, '..', 'firefox-ios', 'Ecosia', 'UI', 'DesignSystem', 'EcosiaColor.swift');
const PRIMITIVE_FILE = '01.color-primitive.tokens.json';

// ── 1. Load token file ───────────────────────────────────────────────────────

const primitivePath = path.join(TOKENS_DIR, PRIMITIVE_FILE);
if (!fs.existsSync(primitivePath)) {
  console.log(`ℹ️  ${PRIMITIVE_FILE} not in this push — nothing to generate.`);
  process.exit(0);
}

const primitives = JSON.parse(fs.readFileSync(primitivePath, 'utf8'));

// ── 2. Build reference resolver ──────────────────────────────────────────────

function buildRefMap(obj, prefix) {
  prefix = prefix || '';
  const map = {};
  for (const key of Object.keys(obj)) {
    const val  = obj[key];
    const addr = prefix ? `${prefix}.${key}` : key;
    if (val && val.$value !== undefined) {
      map[addr] = val.$value;
    } else if (val && typeof val === 'object' && !Array.isArray(val)) {
      Object.assign(map, buildRefMap(val, addr));
    }
  }
  return map;
}

const refMap = buildRefMap(primitives);

function resolve(value, depth) {
  depth = depth || 0;
  if (depth > 10 || !value) return value;
  const m = String(value).match(/^\{(.+)\}$/);
  return m ? resolve(refMap[m[1]], depth + 1) : value;
}

// ── 3. Naming helpers ────────────────────────────────────────────────────────

// "Dark_Green" → "DarkGreen", "Light_Green" → "LightGreen", "Neutral" → "Neutral"
function groupPrefix(group) {
  return group
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

// "gray-10"       → "10"
// "Grellow-100"   → "100"
// "dark-green-30" → "30"
// "white"         → "White"   (Neutral group special case)
// "black"         → "Black"
function tokenSuffix(key) {
  const m = key.match(/(\d+)$/);
  return m ? m[1] : key.charAt(0).toUpperCase() + key.slice(1);
}

function toSwiftHex(hex) {
  return '0x' + hex.replace('#', '').slice(0, 6).toUpperCase();
}

// ── 4. Collect all entries ───────────────────────────────────────────────────

const sections = [];

for (const group of Object.keys(primitives)) {
  const tokens  = primitives[group];
  const prefix  = groupPrefix(group);
  const entries = [];

  for (const key of Object.keys(tokens)) {
    const meta = tokens[key];
    if (!meta || meta.$type !== 'color') continue;

    const resolved = resolve(meta.$value);
    if (!resolved || !String(resolved).startsWith('#')) {
      console.warn(`⚠️  Could not resolve ${group}.${key} = ${meta.$value}`);
      continue;
    }

    entries.push({
      name: `${prefix}${tokenSuffix(key)}`,
      hex:  toSwiftHex(resolved),
    });
  }

  if (entries.length > 0) {
    sections.push({ group, entries });
  }
}

// ── 5. Render Swift ──────────────────────────────────────────────────────────

const header = `\
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/
//
// ⚠️  AUTO-GENERATED — do not edit by hand.
// Source: design-tokens/${PRIMITIVE_FILE}
// Regenerated by: .github/workflows/sync-design-tokens.yml

import UIKit

// https://www.figma.com/design/8T2rTBVwynJKSdY6MQo5PQ/%E2%9A%9B%EF%B8%8F--Foundations
// You should never call those colors directly, they should only be called from a theme within the theme manager.
public struct EcosiaColor {
`;

let body = '';

for (const { group, entries } of sections) {
  const label     = group.replace(/_/g, ' ');
  const maxLen    = Math.max(...entries.map(e => e.name.length));

  body += `    // MARK: - ${label}\n`;
  for (const { name, hex } of entries) {
    body += `    public static let ${name.padEnd(maxLen)} = UIColor(rgb: ${hex})\n`;
  }
  body += '\n';
}

const output = header + body + '}\n';

// ── 6. Write only if content changed ────────────────────────────────────────

const existing = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : '';

// Strip the auto-generated header timestamp lines before comparing
const normalize = s => s.replace(/\/\/ Regenerated by:.*\n/, '');

if (normalize(output) === normalize(existing)) {
  console.log('✅  EcosiaColor.swift is already up to date.');
} else {
  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`✅  Written: ${OUTPUT_PATH}`);
}
