name: 'Perform Unit Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
        
    - name: Run tests with xcodebuild
      shell: bash
      run: |
        xcodebuild -scheme Ecosia \
          -project firefox-ios/Client.xcodeproj \
          -configuration Testing \
          -enableCodeCoverage NO \
          -testPlan UnitTest \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -resultBundlePath TestResults.xcresult \
          clean build test
        
    - name: Convert xcresult to JUnit format
      if: always()
      shell: bash
      run: |
        # Create output directory
        mkdir -p test_output/xml
        
        # Install xcresultparser if needed
        if ! command -v xcresultparser &> /dev/null; then
          brew install chargepoint/xcparse/xcparse
        fi
        
        # Convert xcresult to JUnit format
        xcparse exportJUnit TestResults.xcresult test_output/xml/report.junit
        
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}