name: 'Perform Unit Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
        
    - name: Build the app for testing
      shell: bash
      run: bundle exec fastlane run run_tests clean:true build_for_testing:true

    - name: Run the tests
      shell: bash
      run: |
        # Set environment variables to suppress warnings and errors
        export OTHER_SWIFT_FLAGS="-suppress-warnings"
        export SWIFT_TREAT_WARNINGS_AS_ERRORS=NO
        export SWIFT_STRICT_CONCURRENCY=minimal
        
        # Skip BrazeServiceTests to avoid dependency issues
        bundle exec fastlane run run_tests test_without_building:true skip_testing:"EcosiaTests/BrazeServiceTests"

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}