name: 'Perform Unit Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
        
    - name: Run Unit Tests
      shell: bash
      run: |
        # Skip tests that require BrazeKit to avoid dependency issues
        bundle exec fastlane run run_tests skip_testing:"EcosiaTests/BrazeServiceTests"

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}