name: 'Perform Unit Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:

    - name: Verify Simulator Status
      shell: bash
      run: |
        echo "Checking simulator status..."
        xcrun simctl list devices | grep -A 5 "iPhone16-iOS18.2" || {
          echo "Error: iPhone16-iOS18.2 simulator not found"
          echo "Available devices:"
          xcrun simctl list devices
          exit 1
        }
        
    - name: Run Unit Tests
      shell: bash
      run: |
        bundle exec fastlane run run_tests

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}