name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:  
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@db5138dc428575c0c2245f2f04b58921b2ecc825 # v0.29
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # from https://github.com/qodo-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
          github_action_config.auto_review: "true" 
          github_action_config.auto_describe: "false" 
          github_action_config.auto_improve: "true" 
          github_action_config.enable_output: "false"
          pr_reviewer.inline_code_comments: "true" 
          pr_reviewer.num_code_suggestions: 5
          pr_reviewer.enable_review_labels_effort: "false" 
